source "https://rubygems.org"
gem "rails", "8.0.5.1"
gem "puma", "8.0.2"
gem "rack", "3.2.7"
gem "sqlite3", "2.9.6", platforms: :mri
gem "activerecord-jdbcsqlite3-adapter", "80.0.pre1", platforms: :jruby
gem "jdbc-sqlite3", "3.46.1.1", platforms: :jruby
gem "propshaft", "1.3.2"
gem "importmap-rails", "2.2.3"
gem "turbo-rails", "2.0.23"
gem "stimulus-rails", "1.3.4"
gem "jbuilder", "2.15.1"
gem "tailwindcss-rails", "4.6.0", platforms: :mri
